CREATE DATABASE PROVIVI;

USE PROVIVI;

CREATE TABLE IF NOT EXISTS `USER_FIRST_NAME`(
   `USER_FIRST_NAME_ID` INT UNSIGNED AUTO_INCREMENT,
   `USER_FIRST_NAME_DESC` VARCHAR(100) NOT NULL,
   `CREATION_TS` DATE,
   `CREATED_BY` VARCHAR(40),
   'MODIFICATION_TS' DATE,
   `MODIFIED_BY` VARCHAR(40),
   PRIMARY KEY ( `USER_FIRST_NAME_ID` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `USER_MIDDLE_NAME`(
   `USER_MIDDLE_NAME_ID` INT UNSIGNED AUTO_INCREMENT,
   `USER_MIDDLE_NAME_DESC` VARCHAR(100) NOT NULL,
   `CREATION_TS` DATE,
   `CREATED_BY` VARCHAR(40),
   'MODIFICATION_TS' DATE,
   `MODIFIED_BY` VARCHAR(40),
   PRIMARY KEY ( `USER_MIDDLE_NAME_ID` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `USER_LAST_NAME`(
   `USER_LAST_NAME_ID` INT UNSIGNED AUTO_INCREMENT,
   `USER_LAST_NAME_DESC` VARCHAR(100) NOT NULL,
   `CREATION_TS` DATE,
   `CREATED_BY` VARCHAR(40),
   'MODIFICATION_TS' DATE,
   `MODIFIED_BY` VARCHAR(40),
   PRIMARY KEY ( `USER_LAST_NAME_ID` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USER_FIRST_NAME 
(USER_FIRST_NAME_DESC, CREATION_TS, CREATED_BY) 
VALUES ('Jane', SYSDATE(), 'likun');


INSERT INTO USER_MIDDLE_NAME 
(USER_MIDDLE_NAME_DESC, CREATION_TS, CREATED_BY)
VALUES ('Smith', SYSDATE(), 'likun');

INSERT INTO USER_LAST_NAME 
(USER_LAST_NAME_DESC, CREATION_TS, CREATED_BY)
VALUES ('Doe', SYSDATE(), 'likun');